import "./globals.css";
import type { Metadata } from "next";
import { Poppins, Roboto_Mono } from "next/font/google";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto-mono",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${roboto_mono.variable}`}>
      <body className="min-h-screen">
        <nav className="px-3 fixed w-screen top-0 bg-white z-10 ">
          <div className=" h-full  w-full max-w-xl lg:max-w-4xl xl:max-w-7xl mx-auto  flex items-center ">
            <div className="border-2 border-black  w-full flex  justify-between items-center py-2 my-2  px-4 rounded-md shadow-md">
              <p>Plerion</p>
              <ul className="flex gap-4  items-center">
                <li>
                  <p>Home</p>
                </li>
                <li>
                  <p>Products</p>
                </li>
                <li>
                  <p>Login</p>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <main className="max-w-xl lg:max-w-4xl xl:max-w-7xl mx-auto px-3 mb-4 mt-[60px]">
          {children}
        </main>
        <div id="plerion-modal"></div>
      </body>
    </html>
  );
}
